FROM ubuntu

ENV TEAMS_URI "https://outlook.office.com/webhook/493392e8-3d3b-460c-971c-88348f005ae1@a0b7abdc-4546-4076-abae-426f01df18b2/IncomingWebhook/defa5c760eff462688ade76be8ce0dc0/c4fac366-bcfc-454c-b3cf-8b57e1b44f19"

WORKDIR /opt/ex3

#Install dependency
RUN apt-get update; apt-get install curl -y

#Copy JSON
COPY ./src .

#Post
CMD curl -vX POST $TEAMS_URI -d @test.json --header "Content-Type: application/json"
