FROM microsoft/dotnet:sdk AS builder

WORKDIR /opt/build

COPY ./src .

RUN dotnet restore 

RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:aspnetcore-runtime

WORKDIR /opt/app

COPY --from=builder /opt/build/out .

CMD ["dotnet", "dotnet-core-hello-world.dll"]

